INSERT INTO airport_handling_services (service_type, airport, basic_price, sell_price, additional, additional_basic_price, porter_base_price, porter_base_quantity, porter_additional_price, services_arrival, services_departure, terminal, trip_type, category) VALUES
('VIP Meet & Greet', 'Soekarno-Hatta International Airport', 150000, 200000, 25000, 0, 0, 3, 0, 'VIP meet and greet service for arrival passengers', 'VIP meet and greet service for departure passengers', 'Terminal 1', 'Arrival', 'VIP Service'),
('VIP Meet & Greet', 'Soekarno-Hatta International Airport', 150000, 200000, 25000, 0, 0, 3, 0, 'VIP meet and greet service for arrival passengers', 'VIP meet and greet service for departure passengers', 'Terminal 2', 'Departure', 'VIP Service'),
('Fast Track', 'Soekarno-Hatta International Airport', 100000, 150000, 20000, 0, 0, 3, 0, 'Fast track immigration clearance service', 'Fast track immigration clearance service', 'Terminal 1', 'Both', 'Immigration'),
('Lounge Access', 'Soekarno-Hatta International Airport', 200000, 300000, 40000, 0, 0, 3, 0, 'Premium lounge access with complimentary food and beverages', 'Premium lounge access with complimentary food and beverages', 'Terminal 2', 'Both', 'Lounge'),
('Wheelchair Service', 'Soekarno-Hatta International Airport', 50000, 75000, 10000, 0, 0, 3, 0, 'Wheelchair assistance for passengers with mobility needs', 'Wheelchair assistance for passengers with mobility needs', 'All Terminals', 'Both', 'Assistance'),
('Porter', 'Soekarno-Hatta International Airport', 30000, 70000, 15000, 8000, 70000, 3, 20000, 'Professional baggage handling and porter service', 'Professional baggage handling and porter service', 'All Terminals', 'Both', 'Baggage Handling'),
('VIP Meet & Greet', 'Ngurah Rai International Airport', 140000, 180000, 22000, 0, 0, 3, 0, 'VIP meet and greet service for arrival passengers', 'VIP meet and greet service for departure passengers', 'International Terminal', 'Arrival', 'VIP Service'),
('VIP Meet & Greet', 'Ngurah Rai International Airport', 140000, 180000, 22000, 0, 0, 3, 0, 'VIP meet and greet service for arrival passengers', 'VIP meet and greet service for departure passengers', 'Domestic Terminal', 'Departure', 'VIP Service'),
('Fast Track', 'Ngurah Rai International Airport', 90000, 130000, 18000, 0, 0, 3, 0, 'Fast track immigration clearance service', 'Fast track immigration clearance service', 'International Terminal', 'Both', 'Immigration'),
('Porter', 'Ngurah Rai International Airport', 25000, 70000, 12000, 5000, 70000, 3, 20000, 'Professional baggage handling and porter service', 'Professional baggage handling and porter service', 'All Terminals', 'Both', 'Baggage Handling');
