DROP FUNCTION IF EXISTS upsert_stock;

CREATE OR REPLACE FUNCTION upsert_stock(
  p_name TEXT,
  p_category TEXT[],
  p_warehouse_location TEXT,
  p_item_name TEXT,
  p_unit TEXT,
  p_supplier_name TEXT,
  p_quantity INTEGER,
  p_ppn_type TEXT,
  p_purchase_price NUMERIC,
  p_ppn_beli NUMERIC,
  p_harga_beli_setelah_ppn NUMERIC,
  p_selling_price NUMERIC,
  p_ppn_jual NUMERIC,
  p_harga_jual_setelah_ppn NUMERIC,
  p_part_number TEXT,
  p_brand TEXT[],
  p_location TEXT,
  p_model TEXT,
  p_vehicle_type TEXT,
  p_plate_number TEXT,
  p_created_by UUID
)
RETURNS void AS $$
BEGIN
  INSERT INTO public.stock (
    name,
    category,
    warehouse_location,
    item_name,
    unit,
    supplier_name,
    quantity,
    ppn_type,
    purchase_price,
    ppn_beli,
    harga_beli_setelah_ppn,
    selling_price,
    ppn_jual,
    harga_jual_setelah_ppn,
    part_number,
    brand,
    location,
    model,
    vehicle_type,
    plate_number,
    created_by,
    created_at,
    updated_at
  ) VALUES (
    p_name,
    p_category,
    p_warehouse_location,
    p_item_name,
    p_unit,
    p_supplier_name,
    p_quantity,
    p_ppn_type,
    p_purchase_price,
    p_ppn_beli,
    p_harga_beli_setelah_ppn,
    p_selling_price,
    p_ppn_jual,
    p_harga_jual_setelah_ppn,
    p_part_number,
    p_brand,
    p_location,
    p_model,
    p_vehicle_type,
    p_plate_number,
    p_created_by,
    NOW(),
    NOW()
  )
  ON CONFLICT (warehouse_location, item_name, unit)
  DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    supplier_name = EXCLUDED.supplier_name,
    quantity = EXCLUDED.quantity,
    ppn_type = EXCLUDED.ppn_type,
    purchase_price = EXCLUDED.purchase_price,
    ppn_beli = EXCLUDED.ppn_beli,
    harga_beli_setelah_ppn = EXCLUDED.harga_beli_setelah_ppn,
    selling_price = EXCLUDED.selling_price,
    ppn_jual = EXCLUDED.ppn_jual,
    harga_jual_setelah_ppn = EXCLUDED.harga_jual_setelah_ppn,
    part_number = EXCLUDED.part_number,
    brand = EXCLUDED.brand,
    location = EXCLUDED.location,
    model = EXCLUDED.model,
    vehicle_type = EXCLUDED.vehicle_type,
    plate_number = EXCLUDED.plate_number,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql;
