-- Add PPN fields to stock table
ALTER TABLE public.stock 
ADD COLUMN IF NOT EXISTS ppn_type text NOT NULL DEFAULT 'Non PPN',
ADD COLUMN IF NOT EXISTS ppn_beli DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ppn_jual DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS harga_beli_setelah_ppn DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS harga_jual_setelah_ppn DECIMAL(10,2) DEFAULT 0;
